<body>
<div id="wrapper">
    <div class="main-container">
        <div class="container">
            <div class="row">
                <div class="col-md-9 page-content">
                    <div class="inner-box category-content">
                        <h2 class="title-2 uppercase"><strong> <i class="icon-docs"></i> Anuncie grátis
                                </strong></h2>

                        <div class="row">
                            <div class="col-sm-12">
                                <form class="form-horizontal" action="<?php $this->basePath("anuncio/cadastrar")?>" method="post">
                                    <fieldset>
                                        <!-- Select Basic -->
                                        <div class="form-group">
                                            <label class="col-md-3 control-label">Categoria</label>

                                            <div class="col-md-8">
                                                <select name="categoria-grupo" id="categoria-grupo" class="form-control">
                                                    <option value="0" selected="selected"> Selecione uma categoria...</option>
                                                    <option value="Veículos"
                                                            style="background-color:#E9E9E9;font-weight:bold;"
                                                            disabled="disabled"> - Veículos -
                                                    </option>
                                                    <option value="Carros"> Carros</option>
                                                    <option value="Motos"> Motos</option>
                                                    <option value="Equipamentos para motos/carros"> Equipamentos para motos/carros
                                                    </option>
                                                    <option value="Barcos"> Barcos</option>
                                                    <option value="Vehicles"> Outros veículos</option>
                                                    <option value="House"
                                                            style="background-color:#E9E9E9;font-weight:bold;"
                                                            disabled="disabled"> - House and Children -
                                                    </option>
                                                    <option value="Appliances"> Appliances</option>
                                                    <option value="Inside"> Inside</option>
                                                    <option value="Games"> Games and Clothing</option>
                                                    <option value="Garden"> Garden</option>
                                                    <option value="Multimedia"
                                                            style="background-color:#E9E9E9;font-weight:bold;"
                                                            disabled="disabled"> - Multimedia -
                                                    </option>
                                                    <option value="Telephony"> Telephony</option>
                                                    <option value="Image"> Image and sound</option>
                                                    <option value="Computers"> Computers and Accessories</option>
                                                    <option value="Video"> Video games and consoles</option>
                                                    <option value="Real"
                                                            style="background-color:#E9E9E9;font-weight:bold;"
                                                            disabled="disabled"> - Real Estate -
                                                    </option>
                                                    <option value="Apartment"> Apartment</option>
                                                    <option value="Home"> Home</option>
                                                    <option value="Vacation"> Vacation Rentals</option>
                                                    <option value="Commercial"> Commercial offices and local</option>
                                                    <option value="Grounds"> Grounds</option>
                                                    <option value="Houseshares"> Houseshares</option>
                                                    <option value="Other real estate"> Other real estate</option>
                                                    <option value="Services"
                                                            style="background-color:#E9E9E9;font-weight:bold;"
                                                            disabled="disabled"> - Services -
                                                    </option>
                                                    <option value="Jobs"> Jobs</option>
                                                    <option value="Job application"> Job application</option>
                                                    <option value="Services"> Services</option>
                                                    <option value="Price"> Price</option>
                                                    <option value="Business"> Business and goodwill</option>
                                                    <option value="Professional"> Professional equipment</option>
                                                    <option value="dropoff"
                                                            style="background-color:#E9E9E9;font-weight:bold;"
                                                            disabled="disabled"> - Extra -
                                                    </option>
                                                    <option value="Other"> Other</option>
                                                </select>
                                            </div>
                                        </div>

                                        <!-- Multiple Radios (inline) -->
                                        <div class="form-group">
                                            <label class="col-md-3 control-label">Tipo do anúncio</label>

                                            <div class="col-md-8">
                                                <label class="radio-inline" for="tipo-anuncio-0">
                                                    <input name="tipo-anuncio" id="tipo-anuncio-0" value="Particular" checked="checked"
                                                           type="radio">
                                                    Particular </label>
                                                <label class="radio-inline" for="tipo-anuncio-1">
                                                    <input name="tipo-anuncio" id="tipo-anuncio-1" value="Profissional" type="radio">
                                                    Profissional </label>
                                            </div>
                                        </div>

                                        <!-- Text input-->
                                        <div class="form-group">
                                            <label class="col-md-3 control-label" for="titulo">Título</label>

                                            <div class="col-md-8">
                                                <input id="titulo" name="titulo" placeholder="Título"
                                                       class="form-control input-md" required="" type="text">
                                                <span class="help-block">Um bom título necessita pelo menos 60 caracteres. </span>
                                            </div>
                                        </div>

                                        <!-- Textarea -->
                                        <div class="form-group">
                                            <label class="col-md-3 control-label" for="descricao">Descrição do anúncio</label>

                                            <div class="col-md-8">
                                                <textarea class="form-control" id="descricao" name="descricao"></textarea>
                                            </div>
                                        </div>

                                        <!-- Prepended text-->
                                        <div class="form-group">
                                            <label class="col-md-3 control-label" for="preco">Preço</label>

                                            <div class="col-md-4">
                                                <div class="input-group"><span class="input-group-addon">R$</span>
                                                    <input id="preco" name="preco" class="form-control"
                                                           placeholder="Preço" required="" type="text">
                                                </div>
                                            </div>
                                            <!--<div class="col-md-4">
                                                <div class="checkbox">
                                                    <label>
                                                        <input type="checkbox">
                                                        Negociável </label>
                                                </div>
                                            </div>-->
                                        </div>

                                        <!-- photo -->
                                        <div class="form-group">
                                            <label class="col-md-3 control-label" for="textarea"> Fotos </label>

                                            <div class="col-md-8">
                                                <div class="mb10">
                                                    <input id="input-upload-img1" type="file" class="file"
                                                           data-preview-file-type="text">
                                                </div>
                                                <div class="mb10">
                                                    <input id="input-upload-img2" type="file" class="file"
                                                           data-preview-file-type="text">
                                                </div>
                                                <div class="mb10">
                                                    <input id="input-upload-img3" type="file" class="file"
                                                           data-preview-file-type="text">
                                                </div>
                                                <div class="mb10">
                                                    <input id="input-upload-img4" type="file" class="file"
                                                           data-preview-file-type="text">
                                                </div>
                                                <div class="mb10">
                                                    <input id="input-upload-img5" type="file" class="file"
                                                           data-preview-file-type="text">
                                                </div>
                                                <p class="help-block">Adicione até 5 fotos reais do produto. Não use
                                                    fotos de catálogos.</p>
                                            </div>
                                        </div>
                                        <div class="content-subheading"><i class="icon-user fa"></i> <strong>Informações
                                            sobre o vendedor</strong></div>

                                        <!-- Text input-->
                                        <div class="form-group">
                                            <label class="col-md-3 control-label" for="textinput-name">Nome</label>

                                            <div class="col-md-8">
                                                <input id="textinput-name" name="textinput-name"
                                                       placeholder="Nome" class="form-control input-md"
                                                       required="" type="text">
                                            </div>
                                        </div>

                                        <!-- Appended checkbox -->
                                        <div class="form-group">
                                            <label class="col-md-3 control-label" for="seller-email"> Email</label>

                                            <div class="col-md-8">
                                                <input id="seller-email" name="seller-email" class="form-control"
                                                       placeholder="Email" required="" type="text">

                                                <!--<div class="checkbox">
                                                    <label>
                                                        <input type="checkbox" value="">
                                                        <small> Ocultar telefone no anúncio.</small>
                                                    </label>
                                                </div>-->
                                            </div>
                                        </div>

                                        <!-- Text input-->
                                        <div class="form-group">
                                            <label class="col-md-3 control-label" for="seller-Number">Telefone</label>

                                            <div class="col-md-8">
                                                <input id="seller-Number" name="seller-Number"
                                                       placeholder="Telefone" class="form-control input-md"
                                                       required="" type="text">
                                            </div>
                                        </div>

                                        <!-- Select Basic -->
                                        <div class="form-group">
                                            <label class="col-md-3 control-label" for="seller-Location">Estado</label>

                                            <div class="col-md-8">
                                                <select id="seller-Location" name="seller-Location"
                                                        class="form-control">
                                                    <option value="1">Option one</option>
                                                    <option value="2">Option two</option>
                                                </select>
                                            </div>
                                        </div>

                                        <!-- Select Basic -->
                                        <div class="form-group">
                                            <label class="col-md-3 control-label" for="seller-area">Cidade</label>

                                            <div class="col-md-8">
                                                <select id="seller-area" name="seller-area" class="form-control">
                                                    <option value="1">Option one</option>
                                                    <option value="2">Option two</option>
                                                </select>
                                            </div>
                                        </div>


                                        <!-- Div do pagamento
                                        <div class="well">
                                            <h3><i class=" icon-certificate icon-color-1"></i> Make your Ad Premium
                                            </h3>

                                            <p>Premium ads help sellers promote their product or service by getting
                                                their ads more visibility with more
                                                buyers and sell what they want faster. <a href="help.html">Learn
                                                    more</a></p>

                                            <div class="form-group">
                                                <table class="table table-hover checkboxtable">
                                                    <tr>
                                                        <td>
                                                            <div class="radio">
                                                                <label>
                                                                    <input type="radio" name="optionsRadios"
                                                                           id="optionsRadios0" value="option0" checked>
                                                                    <strong>Regular List </strong> </label>
                                                            </div>
                                                        </td>
                                                        <td><p>$00.00</p></td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <div class="radio">
                                                                <label>
                                                                    <input type="radio" name="optionsRadios"
                                                                           id="optionsRadios1" value="option1">
                                                                    <strong>Urgent Ad </strong> </label>
                                                            </div>
                                                        </td>
                                                        <td><p>$10.00</p></td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <div class="radio">
                                                                <label>
                                                                    <input type="radio" name="optionsRadios"
                                                                           id="optionsRadios2" value="option2">
                                                                    <strong>Top of the Page Ad </strong> </label>
                                                            </div>
                                                        </td>
                                                        <td><p>$20.00</p></td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <div class="radio">
                                                                <label>
                                                                    <input type="radio" name="optionsRadios"
                                                                           id="optionsRadios3" value="option3">
                                                                    <strong>Top of the Page Ad + Urgent Ad </strong>
                                                                </label>
                                                            </div>
                                                        </td>
                                                        <td><p>$40.00</p></td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <div class="form-group">
                                                                <div class="col-md-8">
                                                                    <select class="form-control" name="Method"
                                                                            id="PaymentMethod">
                                                                        <option value="2">Select Payment Method</option>
                                                                        <option value="3">Credit / Debit Card</option>
                                                                        <option value="5">Paypal</option>
                                                                    </select>
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td><p><strong>Payable Amount : $40.00</strong></p></td>
                                                    </tr>
                                                </table>

                                            </div>
                                        </div> -->

                                        <!-- terms -->
                                        <!--<div class="form-group">
                                            <label class="col-md-3 control-label">Terms</label>

                                            <div class="col-md-8">
                                                <label class="checkbox-inline" for="checkboxes-0">
                                                    <input name="checkboxes" id="checkboxes-0"
                                                           value="Remember above contact information." type="checkbox">
                                                    Remember above contact information. </label>
                                            </div>
                                        </div>-->

                                        <!-- Button  -->
                                        <div class="form-group">
                                            <label class="col-md-3 control-label"></label>

                                            <div class="col-md-8"><a href="" id="button1id"
                                                                     class="btn btn-success btn-lg">Enviar</a></div>
                                        </div>
                                    </fieldset>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.page-content -->

                <div class="col-md-3 reg-sidebar">
                    <div class="reg-sidebar-inner text-center">
                        <div class="promo-text-box"><i class=" icon-picture fa fa-4x icon-color-1"></i>

                            <h3><strong>Post a Free Classified</strong></h3>

                            <p> Post your free online classified ads with us. Lorem ipsum dolor sit amet, consectetur
                                adipiscing elit. </p>
                        </div>

                        <div class="panel sidebar-panel">
                            <div class="panel-heading uppercase">
                                <small><strong>How to sell quickly?</strong></small>
                            </div>
                            <div class="panel-content">
                                <div class="panel-body text-left">
                                    <ul class="list-check">
                                        <li> Use a brief title and description of the item</li>
                                        <li> Make sure you post in the correct category</li>
                                        <li> Add nice photos to your ad</li>
                                        <li> Put a reasonable price</li>
                                        <li> Check the item before publish</li>

                                    </ul>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
                <!--/.reg-sidebar-->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </div>
    <!-- /.main-container -->
</div>
<!-- /.wrapper -->

<!-- Le javascript
================================================== -->
<!-- include jquery file upload plugin  -->
<?= $this->inlineScript()
    //->prependFile($this->basePath('assets/js/fileinput.min.js'))
?>
<script>
    // initialize with defaults
    //$("#input-upload-img1").fileinput();
    //$("#input-upload-img2").fileinput();
    //$("#input-upload-img3").fileinput();
    //$("#input-upload-img4").fileinput();
    //$("#input-upload-img5").fileinput();


</script>
</body>