<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('MercadoBD - frase de efeito')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <nav class="navbar   navbar-site navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                        <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span
                            class="icon-bar"></span> <span class="icon-bar"></span></button>
                    <a href="/mercadobd/public/" class="navbar-brand logo logo-title">
                        <!-- Original Logo will be placed here  -->
                        <span class="logo-icon"><i class="icon icon-search-1 ln-shadow-logo shape-0"></i> </span>
                        <span>Mercado</span>BD</a></div>
                <div class="navbar-collapse collapse">

                    <ul class="nav navbar-nav navbar-right">
                        <!--<li><a href="login">Login</a></li>
                        <li><a href="login/cadastrar">Cadastrar</a></li>-->
                        <li class="postadd"><a class="btn btn-block btn-border btn-post btn-danger"
                                               href="<?= $this->basePath('/anuncio/cadastrar')?>"><b>ANUNCIE GRÁTIS</b></a></li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
            <!-- /.container-fluid -->
        </nav>
    </head>
    <body>
        <div class="container"  style="padding-top: 65px;">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>

    <!-- Placed at the end of the document so the pages load faster -->

    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>-->

    <!--//$this->inlineScript()
        //->prependFile($this->basePath('assets/bootstrap/js/bootstrap.min.js'))
        //->prependFile($this->basePath('assets/js/owl.carousel.min.js'))
        //->prependFile($this->basePath('assets/js/jquery.matchHeight-min.js'))
        //->prependFile($this->basePath('assets/js/hideMaxListItem.js'))
        //->prependFile($this->basePath('assets/plugins/jquery.fs.scroller/jquery.fs.scroller.js'))
        //->prependFile($this->basePath('assets/plugins/jquery.fs.selecter/jquery.fs.selecter.js'))
        //->prependFile($this->basePath('assets/js/script.js'))
        //->prependFile($this->basePath('assets/plugins/autocomplete/jquery.mockjax.js'))
        //->prependFile($this->basePath('assets/plugins/autocomplete/jquery.autocomplete.js'))
        //->prependFile($this->basePath('assets/plugins/autocomplete/usastates.js'))
        //->prependFile($this->basePath('assets/plugins/autocomplete/autocomplete-demo.js'))
        //->prependFile($this->basePath('assets/js/form-validation.js'))

    -->

    </body>
</html>
