<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('MercadoBD - frase de efeito')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        !-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
        <link rel="shortcut icon" href="assets/ico/favicon.png">

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('assets/css/style.css'))
            ->prependStylesheet($this->basePath('assets/bootstrap/css/bootstrap.css'))
            ->prependStylesheet($this->basePath('assets/css/owl.carousel.css'))
            ->prependStylesheet($this->basePath('assets/css/owl.theme.css'))
        ?>

        <!-- Scripts -->
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>


        <?= $this->headScript()
            ->prependFile($this->basePath('assets/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('assets/js/jquery/jquery-latest.js'))
            ->prependFile($this->basePath('assets/js/pace.min.js'))

        ?>
    </head>
    <body>
    <nav class="navbar   navbar-site navbar-default" role="navigation" style="margin-bottom: 50 px">
        <div class="container">
            <div class="navbar-header">
                <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                    <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span
                        class="icon-bar"></span> <span class="icon-bar"></span></button>
                <a href="index.html" class="navbar-brand logo logo-title">
                    <!-- Original Logo will be placed here  -->
                    <span class="logo-icon"><i class="icon icon-search-1 ln-shadow-logo shape-0"></i> </span>
                    Mercado<span>BD</span> </a></div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="login">Login</a></li>
                    <li><a href="login/cadastrar">Cadastrar</a></li>
                    <li class="postadd"><a class="btn btn-block   btn-border btn-post btn-danger"
                                           href="post-ads.html">ANUNCIE GRÁTIS</a></li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>


    <script src="assets/js/bootstrap.min.js"></script>

    <!-- include carousel slider plugin  -->
    <script src="assets/js/owl.carousel.min.js"></script>

    <!-- include equal height plugin  -->
    <script src="assets/js/jquery.matchHeight-min.js"></script>

    <!-- include jquery list shorting plugin plugin  -->
    <script src="assets/js/hideMaxListItem.js"></script>

    <!-- include jquery.fs plugin for custom scroller and selecter  -->
    <script src="assets/plugins/jquery.fs.scroller/jquery.fs.scroller.js"></script>
    <script src="assets/plugins/jquery.fs.selecter/jquery.fs.selecter.js"></script>


    <!-- include custom script for site  -->
    <script src="assets/js/script.js"></script>

    <!-- include jquery autocomplete plugin  -->

    <script type="text/javascript" src="assets/plugins/autocomplete/jquery.mockjax.js"></script>
    <script type="text/javascript" src="assets/plugins/autocomplete/jquery.autocomplete.js"></script>
    <script type="text/javascript" src="assets/plugins/autocomplete/usastates.js"></script>

    <script type="text/javascript" src="assets/plugins/autocomplete/autocomplete-demo.js"></script>
    </body>
</html>
